### ISSUE TITLE
Syntax highlighting with Prism.js

### ISSUE THREAD

**Issue by dandv** [mojomojo/mojomojo#129]
My Syntax::Highlighter::Engine::Kate got busted for some reason (even though I have the modules installed), so I looked for a client-side syntax highlight library.

Found [Prism.js](http://prismjs.com/). 2KB minified. [MIT-licensed on GitHub](https://github.com/LeaVerou/prism/). Handles pretty much anything. Extremely easy to use:

``` html
<link href="http://prismjs.com/themes/prism-coy.css" rel="stylesheet" />
<script src="http://prismjs.com/prism.js"></script>
<pre><code class="language-javascript">
console.log('Hello world');
</code></pre>
```

Works great on my wiki - http://wiki.dandascalescu.com/howtos/Automating_any_Meteor_app_you_find_on_the_web#Putting_it_all_together

Also, Prism encourages semantically correct markup with `<pre><code class="language-javascript">`. We use `<pre lang=...>` which is technically invalid.

**Comment by marcusramberg** [comment]
Looks great, danvd. Would you like to create a branch to tear out the old syntax higlighter? Less deps would be a win too :+1:

**Comment by dandv** [comment]
There's a problem with it, at least if you add the script and CSS in the page - previewing doesn't work. The `<pre>` looks a bit different, but the Prism styles aren't applied. Only after saving are they applied.

**Comment by marcusramberg** [comment]
You probably need to call highlightelement manually on the preview div
after each render of the preview.

Marcus

**Comment by simonaw** [comment]
@marcusramberg OK, so far. Do you think we can close this one?

**Comment by marcusramberg** [comment]
Yea.
