### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by marcusramberg** [mojomojo/mojomojo#131]
DEPRECATION WARNING: The Regex dispatch type is deprecated.
  The standalone Catalyst::DispatchType::Regex distribution
  has been temporarily included as a prerequisite of
  Catalyst::Runtime, but will be dropped in the future. Convert
  to Chained methods or include Catalyst::DispatchType::Regex
  as a prerequisite for your application.

**Comment by mateu** [comment]
Does this concern MojoMojo, I don''t see any Regex decorated actions?

**Comment by marcusramberg** [comment]
I just got that warning when restarting one of our mojomojo apps. Not sure if we have to do anything, put it in here as a reminder for me to investigate.
