### ISSUE TITLE
CPAN Pull Request Challenge - March 2015

### ISSUE THREAD

**Issue by kaoru** [mojomojo/mojomojo#133]
Hi there,

This month I got MojoMojo as my CPAN Pull Request Challenge. You've probably heard about it, but you can read more here: http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html

It looks like there's plenty of issues open on Github. Any issues in particular that you'd like me to take a look at?

In the meantime I'd like to take a look at getting the distribution in a position that CPAN Testers can run properly on it.

I might also see about getting the schema_DBIC tests working in parallel. Currently they have to be run in serial; they fail if you do "prove -j 2", which is a pet peeve of mine :-)

**Comment by marcusramberg** [comment]
We appreciate any contributions you would like to work on. I think anything lowering the barrier of installation would be most appreciated, like trimming the dependency chain or providing a Dockerfile

**Comment by kaoru** [comment]
Sounds good - I suspect that "lowering the barrier of installation" and "getting CPAN Testers to be able to test the distribution" have a bunch of overlap so that's what I'll target first.

**Comment by marcusramberg** [comment]
:sparkles:
