### ISSUE TITLE
mojomojo.org down

### ISSUE THREAD

**Issue by dandv** [mojomojo/mojomojo#143]
http://isup.me/mojomojo.org

**Comment by simonaw** [comment]
@marcusramberg `whois` says you are the admin. ;)  Is there any chance to get this going again?

**Comment by marcusramberg** [comment]
@simonaw I have DNS admin, but the jail I used to host it on went away when my company failed. Will investigate some other opportunities

**Comment by simonaw** [comment]
@marcusramberg As an intermediate solution you could let it point to the github homepage `https://github.com/mojomojo/mojomojo`, maybe?

**Comment by marcusramberg** [comment]
You'd still need a server to do a http redirect. We could maybe make a simple github pages page tho

**Comment by marcusramberg** [comment]
I've set up a redirect to the github repo for now. Will try to get a demo installation back up later.
