### ISSUE TITLE
Upcoming changes to Text::Multimarkdown

### ISSUE THREAD

**Issue by briandfoy** [mojomojo/mojomojo#157]
I'm making some improvements to Text::MultiMarkdown, and I've [started a GitHub discussion](https://github.com/briandfoy/text-multimarkdown/discussions/9) to give downstreams advance notice and a chance to give feedback before anything happens. I'd like to start doing this with more modules I maintain.

* in progress: briandfoy/text-multimarkdown#6
* an idea for user-defined labels: briandfoy/text-multimarkdown#7

First, the `markdown` function and method that already exists will still be there and should work in the same way. But there will be a better name for this. 

Second, I'll figure out how to test your module with the changes to make sure your tests still pass. I'm tracking this at briandfoy/text-multimarkdown#8

Third, I'll make a pull request with the better interface. You can take it or not because the old way will still work.

Last, tell me this is more than you want to think about and get on with life.

**Comment by marcusramberg** [comment]
I haven't touched this project in 7 years and I have no idea if anyone is still using it ;-)
